<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260702152822 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE trip (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, departure_time TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, price DOUBLE PRECISION NOT NULL, available_seats INT NOT NULL, status VARCHAR(255) NOT NULL, route_id INT NOT NULL, vehicle_id INT NOT NULL, partner_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_7656F53B34ECB4E6 ON trip (route_id)');
        $this->addSql('CREATE INDEX IDX_7656F53B545317D1 ON trip (vehicle_id)');
        $this->addSql('CREATE INDEX IDX_7656F53B9393F8FE ON trip (partner_id)');
        $this->addSql('ALTER TABLE trip ADD CONSTRAINT FK_7656F53B34ECB4E6 FOREIGN KEY (route_id) REFERENCES route (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE trip ADD CONSTRAINT FK_7656F53B545317D1 FOREIGN KEY (vehicle_id) REFERENCES vehicle (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE trip ADD CONSTRAINT FK_7656F53B9393F8FE FOREIGN KEY (partner_id) REFERENCES partner (id) NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE trip DROP CONSTRAINT FK_7656F53B34ECB4E6');
        $this->addSql('ALTER TABLE trip DROP CONSTRAINT FK_7656F53B545317D1');
        $this->addSql('ALTER TABLE trip DROP CONSTRAINT FK_7656F53B9393F8FE');
        $this->addSql('DROP TABLE trip');
    }
}
