<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260702100831 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE city (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE route (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, departure_city_id INT NOT NULL, destination_city_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_2C42079918B251E ON route (departure_city_id)');
        $this->addSql('CREATE INDEX IDX_2C42079E5955DD7 ON route (destination_city_id)');
        $this->addSql('ALTER TABLE route ADD CONSTRAINT FK_2C42079918B251E FOREIGN KEY (departure_city_id) REFERENCES city (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE route ADD CONSTRAINT FK_2C42079E5955DD7 FOREIGN KEY (destination_city_id) REFERENCES city (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE partner ADD status VARCHAR(255) NOT NULL');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE route DROP CONSTRAINT FK_2C42079918B251E');
        $this->addSql('ALTER TABLE route DROP CONSTRAINT FK_2C42079E5955DD7');
        $this->addSql('DROP TABLE city');
        $this->addSql('DROP TABLE route');
        $this->addSql('ALTER TABLE partner DROP status');
    }
}
